"""added gst

Revision ID: 009aa6756065
Revises: 7365a702783c
Create Date: 2022-12-25 18:54:11.314503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009aa6756065'
down_revision = '7365a702783c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('gst')

    # ### end Alembic commands ###
