"""added file to records table

Revision ID: 0ce470571ae1
Revises: 
Create Date: 2022-10-05 17:13:16.401593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce470571ae1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imgupload')
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('data')
        batch_op.drop_column('filename')

    op.create_table('imgupload',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=50), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
