"""to numeric

Revision ID: 2e979324bbe1
Revises: ac6f59660cef
Create Date: 2023-01-04 15:59:10.933376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e979324bbe1'
down_revision = 'ac6f59660cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('final_deal',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('gst',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('bill',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('pending_amount',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('pending_amount_received_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_amount_received_date', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('pending_amount',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('bill',
               existing_type=sa.Numeric(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('gst',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('final_deal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
