"""empty message

Revision ID: 3031d365ea98
Revises: cb12ad4ca5e7
Create Date: 2023-01-07 01:16:19.661182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3031d365ea98'
down_revision = 'cb12ad4ca5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint('records_status_id_fkey', type_='foreignkey')
        batch_op.drop_column('amount')
        batch_op.drop_column('amount_received_date')
        batch_op.drop_column('status_id')
        batch_op.drop_column('pending_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount_received_date', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('records_status_id_fkey', 'status', ['status_id'], ['id'])

    # ### end Alembic commands ###
