"""empty message

Revision ID: 3da1cdeafa68
Revises: ff06c0074635
Create Date: 2023-02-02 20:26:57.882060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3da1cdeafa68'
down_revision = 'ff06c0074635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.alter_column('gst',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.alter_column('gst',
               existing_type=sa.String(length=100),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
