"""removed data

Revision ID: 4c9e6cf8b79d
Revises: fa9dee0f7071
Create Date: 2022-12-22 19:56:50.830878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9e6cf8b79d'
down_revision = 'fa9dee0f7071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
