"""empty message

Revision ID: 54e0c7d64cf5
Revises: 9de4c294d75c
Create Date: 2023-01-23 17:02:05.519100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e0c7d64cf5'
down_revision = '9de4c294d75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('Pending', 'Received', 'Cancelled', name='recordstatus'), nullable=True))
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
