"""added some colums to record table

Revision ID: 5a21628afd3e
Revises: fa53ecb6a63d
Create Date: 2022-10-07 18:54:53.575616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a21628afd3e'
down_revision = 'fa53ecb6a63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_deal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'customer', ['final_deal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('final_deal_id')

    # ### end Alembic commands ###
