"""empty message

Revision ID: 6e0839b044c0
Revises: 4b2906b97fcc
Create Date: 2023-02-15 13:25:38.848205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0839b044c0'
down_revision = '4b2906b97fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_payment_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_payable', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('total_payable')
        batch_op.drop_column('overall_payment_total')

    # ### end Alembic commands ###
