"""empty message

Revision ID: 707371e2ad6d
Revises: 54e0c7d64cf5
Create Date: 2023-01-23 17:07:54.038996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707371e2ad6d'
down_revision = '54e0c7d64cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('credit_amount')

    # ### end Alembic commands ###
