"""empty message

Revision ID: 713116eb0487
Revises: fdc2b6df65b7
Create Date: 2023-01-30 20:32:47.728319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '713116eb0487'
down_revision = 'fdc2b6df65b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    with op.batch_alter_table('payment_voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_order_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('payment_voucher_record_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sales_order', ['sales_order_id'], ['id'])
        batch_op.drop_column('record_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_voucher_record_id_fkey', 'records', ['record_id'], ['id'])
        batch_op.drop_column('sales_order_id')

    op.create_table('records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_advt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_order', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dop', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bill', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bill_date', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount_received_date', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('Pending', 'Received', 'Cancelled', name='recordstatus'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='records_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='records_pkey')
    )
    # ### end Alembic commands ###
