"""update

Revision ID: 7365a702783c
Revises: 3f207d5a437c
Create Date: 2022-12-23 18:56:54.669218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7365a702783c'
down_revision = '3f207d5a437c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Record', schema=None) as batch_op:
        batch_op.drop_index('ix_Record_index')

    op.drop_table('Record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Record',
    sa.Column('index', sa.INTEGER(), nullable=True),
    sa.Column('No', sa.REAL(), nullable=True),
    sa.Column('Client', sa.TEXT(), nullable=True),
    sa.Column('AD/GP/Others', sa.TEXT(), nullable=True),
    sa.Column('RO Date', sa.TEXT(), nullable=True),
    sa.Column('DoP', sa.TEXT(), nullable=True),
    sa.Column('Bill No.', sa.REAL(), nullable=True),
    sa.Column('Bill Date', sa.TEXT(), nullable=True),
    sa.Column('Amount(Rs.)', sa.REAL(), nullable=True),
    sa.Column('Status', sa.TEXT(), nullable=True),
    sa.Column('Pending(Rs.)', sa.REAL(), nullable=True),
    sa.Column('PP Received', sa.TEXT(), nullable=True),
    sa.Column('File Name', sa.TEXT(), nullable=True),
    sa.Column('DATA', sa.TEXT(), nullable=True)
    )
    with op.batch_alter_table('Record', schema=None) as batch_op:
        batch_op.create_index('ix_Record_index', ['index'], unique=False)

    # ### end Alembic commands ###
