"""empty message

Revision ID: 76426aa80c78
Revises: 9b0204e58980
Create Date: 2023-01-10 20:36:56.751384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76426aa80c78'
down_revision = '9b0204e58980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_received_date', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('amount_received_date')

    # ### end Alembic commands ###
