"""empty message

Revision ID: 7652fbfd8f0e
Revises: eb24b47b43c7
Create Date: 2023-03-07 11:55:33.684883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7652fbfd8f0e'
down_revision = 'eb24b47b43c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_expires_at', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_expires_at')

    # ### end Alembic commands ###
