"""empty message

Revision ID: 768a1e2998d8
Revises: d7e2fc350bc8
Create Date: 2023-02-15 17:36:54.369272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768a1e2998d8'
down_revision = 'd7e2fc350bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_payable', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overall_received', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('overall_received')
        batch_op.drop_column('overall_payable')

    # ### end Alembic commands ###
