"""empty message

Revision ID: 7b382b57e742
Revises: 7652fbfd8f0e
Create Date: 2023-03-07 12:39:42.772718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b382b57e742'
down_revision = '7652fbfd8f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('otp_expires_at',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('otp_expires_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
