"""empty message

Revision ID: 85b87d3f42a1
Revises: a11d6c399ca7
Create Date: 2023-01-04 15:07:49.888987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b87d3f42a1'
down_revision = 'a11d6c399ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('phone_no',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('pending_amount_received_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_amount_received_date', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('phone_no',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=0),
               existing_nullable=True)

    # ### end Alembic commands ###
