"""empty message

Revision ID: 8a29081e6780
Revises: 2cf1725ce232
Create Date: 2023-02-15 13:37:54.739273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a29081e6780'
down_revision = '2cf1725ce232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount_received', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('total_amount_received')

    # ### end Alembic commands ###
