"""revert back 0001

Revision ID: 8b76b6766162
Revises: 5a21628afd3e
Create Date: 2022-10-07 19:20:30.154439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b76b6766162'
down_revision = '5a21628afd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_amount', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_records_final_deal_id_final_deal', type_='foreignkey')
        batch_op.drop_column('final_deal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_deal_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_records_final_deal_id_final_deal', 'customer', ['final_deal_id'], ['id'])
        batch_op.drop_column('pending_amount')

    # ### end Alembic commands ###
