"""empty message

Revision ID: 9a0143fcb042
Revises: fdef160c20f4
Create Date: 2023-01-25 16:36:09.567604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0143fcb042'
down_revision = 'fdef160c20f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('Draft', 'Approved', 'Cancelled', name='paymentstatus'), nullable=True))
        batch_op.alter_column('payment_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('approval_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('bill')
        batch_op.drop_column('bill_date')
        batch_op.drop_column('dop')
        batch_op.drop_column('amount_received')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('bill',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('bill',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('payment_voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_received', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dop', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bill_date', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bill', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('approval_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
