"""empty message

Revision ID: 9de4c294d75c
Revises: be11e553735e
Create Date: 2023-01-23 16:00:27.111163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de4c294d75c'
down_revision = 'be11e553735e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('Draft', 'Received', 'Cancelled', name='status'), nullable=True))
        batch_op.drop_constraint('records_status_id_fkey', type_='foreignkey')
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('records_status_id_fkey', 'status', ['status_id'], ['id'])
        batch_op.drop_column('status')

    op.create_table('status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='status_pkey')
    )
    # ### end Alembic commands ###
