"""empty message

Revision ID: a3e1d1526d32
Revises: 707371e2ad6d
Create Date: 2023-01-25 15:02:41.053561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e1d1526d32'
down_revision = '707371e2ad6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymentvoucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_received', sa.String(), nullable=True))
        batch_op.alter_column('payment_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('approval_date',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymentvoucher', schema=None) as batch_op:
        batch_op.alter_column('approval_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('amount_received')

    # ### end Alembic commands ###
