"""empty message

Revision ID: be11e553735e
Revises: 2c17ace85658
Create Date: 2023-01-16 14:56:18.408766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be11e553735e'
down_revision = '2c17ace85658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('phone_no',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('phone_no',
               existing_type=sa.String(length=100),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
