"""removed link column from records table

Revision ID: c9d5556b33c5
Revises: 8b76b6766162
Create Date: 2022-10-07 21:02:23.907166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d5556b33c5'
down_revision = '8b76b6766162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
