"""empty message

Revision ID: d255013c2a07
Revises: 7b382b57e742
Create Date: 2023-03-10 17:51:01.124331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd255013c2a07'
down_revision = '7b382b57e742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_updated_time', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.drop_column('last_updated_time')
        batch_op.drop_column('last_updated_date')

    # ### end Alembic commands ###
