"""empty message

Revision ID: eb24b47b43c7
Revises: 8cbe80534c2e
Create Date: 2023-02-22 14:24:48.886730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb24b47b43c7'
down_revision = '8cbe80534c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adjusted_credit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.drop_column('adjusted_credit')

    # ### end Alembic commands ###
