"""testing addition in db

Revision ID: fa53ecb6a63d
Revises: c11b8c698383
Create Date: 2022-10-07 18:47:12.486928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa53ecb6a63d'
down_revision = 'c11b8c698383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('pending_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_amount', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
