"""removed confirm pass

Revision ID: fa9dee0f7071
Revises: fd12d70d45d7
Create Date: 2022-10-29 18:11:20.851934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9dee0f7071'
down_revision = 'fd12d70d45d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirm_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm_password', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
