"""empty message

Revision ID: ff03761134ba
Revises: f7cbc84c3448
Create Date: 2023-02-15 15:56:17.998975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff03761134ba'
down_revision = 'f7cbc84c3448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount_payable', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('total_amount_payable')

    # ### end Alembic commands ###
